import {chromium} from '@playwright/test';import {createServer} from 'node:http';import {readFile} from 'node:fs/promises';import {TRACK_HEADERS,CONTACT_HEADERS} from './model.js';
const server=createServer(async(req,res)=>{try{const file=decodeURIComponent(req.url.split('?')[0]);if(file.includes('..'))throw 0;const body=await readFile('dist'+(file==='/'?'/index.html':file));res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(body);}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(8787,'127.0.0.1',r));
const browser=await chromium.launch({headless:true});const results=[];
for(const [name,width,height] of [['desktop',1440,1000],['mobile',390,844],['tablet',820,1180]]){
 const ctx=await browser.newContext({viewport:{width,height}});const page=await ctx.newPage();let writes=0;
 let rows=[TRACK_HEADERS,['Candidatura','Example opportunity','Example company','','','<img src=x onerror=alert(1)>','2026-09-30','CV.pdf','Email','CV preparado','Original notes','Test source','https://example.com/cv','test-1'],['Networking','Connection','Example company','','','','','','Email','contato enviado','','','','test-2'],['Candidatura','Submitted opportunity','Another company','','','','2026-09-29','','Email','enviada - recibo confirmado','','','','test-3']];
 await page.route('**/config.js',r=>r.fulfill({contentType:'text/javascript',body:"export const config={clientId:'fake',appId:'fake',pickerKey:'fake'};"}));
 await page.route('https://accounts.google.com/gsi/client',r=>r.fulfill({contentType:'text/javascript',body:`window.google={accounts:{oauth2:{initTokenClient:o=>({requestAccessToken:()=>o.callback({access_token:'synthetic',expires_in:3600})}),revoke:(t,c)=>c()}}};`}));
 await page.route('https://apis.google.com/js/api.js',r=>r.fulfill({contentType:'text/javascript',body:`window.gapi={load:(n,c)=>{google.picker={ViewId:{SPREADSHEETS:'s'},Action:{PICKED:'picked'},DocsView:class{setIncludeFolders(){return this}},PickerBuilder:class{addView(){return this}setOAuthToken(){return this}setDeveloperKey(){return this}setAppId(){return this}setOrigin(){return this}setCallback(c){this.c=c;return this}build(){const c=this.c;return {setVisible:()=>{window.picks=(window.picks||0)+1;c({action:'picked',docs:[{id:window.picks===1?'tracker-test':'contacts-test'}]})}}}}};c()}};`}));
 await page.route('https://www.googleapis.com/oauth2/v3/userinfo',r=>r.fulfill({json:{email:'owner@example.com',email_verified:true}}));
 await page.route('https://sheets.googleapis.com/**',r=>{const url=r.request().url();if(r.request().method()==='PUT'){writes++;const vals=r.request().postDataJSON().values[0];rows[1][9]=vals[0];rows[1][10]=vals[1];return r.fulfill({json:{updatedCells:2}});}if(url.includes('/values/'))return r.fulfill({json:{values:url.includes('tracker-test')?rows:[CONTACT_HEADERS,['Example person','Example company','Test role','Test area','','person@example.com','https://example.com','2026-09-28','Contato mapeado','No reminder scheduled','Synthetic source']]}});return r.fulfill({json:{spreadsheetId:url.includes('tracker-test')?'tracker-test':'contacts-test',properties:{title:'Synthetic sheet'},sheets:(url.includes('tracker-test')?['Candidaturas']:['Pessoas - geral','Pessoas - Example Corp A','Pessoas - Example Agency','Pessoas - Example Corp B']).map(title=>({properties:{title}}))}});});
 await page.goto('http://127.0.0.1:8787');await page.screenshot({path:'/downloads/ponte-'+name+'-landing.png',fullPage:true});
 await page.getByRole('button',{name:'Conectar com Google',exact:true}).click();await page.getByLabel('E-mail da conta Google').fill('owner@example.com');await page.getByRole('button',{name:'Continuar',exact:true}).click();
 await page.getByRole('button',{name:'Selecionar rastreador',exact:true}).click();await page.getByRole('button',{name:'Selecionar contatos',exact:true}).click();await page.getByRole('button',{name:'Central de vagas',exact:true}).waitFor();await page.screenshot({path:'/downloads/ponte-'+name+'-dashboard.png',fullPage:true});
 await page.getByRole('button',{name:'Central de vagas',exact:true}).click();await page.screenshot({path:'/downloads/ponte-'+name+'-central.png',fullPage:true});
 await page.getByRole('button',{name:'Detalhes',exact:true}).first().click();await page.getByLabel('Notas',{exact:true}).fill('Cancelled');await page.getByRole('button',{name:'Cancelar',exact:true}).click();if(writes!==0)throw new Error('Cancel wrote');
 await page.getByRole('button',{name:'Detalhes',exact:true}).first().click();await page.locator('dialog #edit-status').fill('enviada');await page.getByLabel('Notas',{exact:true}).fill('Verified note');await page.getByRole('button',{name:'Salvar',exact:true}).click();await page.getByText('Status e Notas conferidos na planilha.').waitFor();if(writes!==1)throw new Error('Missing save');
 await page.getByRole('button',{name:'Rede',exact:true}).click();await page.getByRole('heading',{name:'Example person'}).first().waitFor();await page.screenshot({path:'/downloads/ponte-'+name+'-network.png',fullPage:true});
 await page.getByRole('button',{name:'EN',exact:true}).click();await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Disconnect',exact:true}).click();await page.getByRole('button',{name:'Connect with Google',exact:true}).waitFor();if((await page.content()).includes('Example person'))throw new Error('Private rows retained');
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw new Error(name+' overflows');results.push({name,flows:'connect, select files, dashboard, central, cancel no write, save verified, network, language, disconnect clears',passed:true});await ctx.close();
}
console.log(JSON.stringify(results,null,2));await browser.close();server.close();
